### ISSUE TITLE
Colorado voting info

### ISSUE THREAD

**Issue by hobbes7878** [The-Politico/politico-civic-almanac#22]
> To Whom it May Concern,
>
> I was looking through your election calendar today and noticed a date under Colorado that was incorrect.
>
> Currently you have that someone can register to vote in person by “June 18”. Colorado has same-day voter registration, so actually this should say June 26th. June 18th is correctly listed as the last date you can apply for a ballot and receive one in the mail.
>
> I also noticed that under “Vote by Mail” you have the heading “mail in by” listed with election day in both the primary and general. If possible, you may consider revising this description, as I worry it may give voters the impression that they only have to have their ballot postmarked by that date. In Colorado, ballots must be received by the county clerks by 7 p.m. on election day in order for their ballot to count- a postmark does not count. A more precise title for this might be “deliver to clerk by” or “deliver by” or something like that.
>
> Please feel free to give me a call or shoot me an email if you would like to discuss this in further detail.
>
> Thank you for your consideration,
>
> Caleb Thornton
> Legal Analyst
> Elections Division | Colorado Department of State
> 1700 Broadway | Suite 200 | Denver | CO | 80290
> Phone 303-894-2200 x6386
> caleb.thornton@sos.state.co.us

**Comment by TylerFisher** [comment]
Fixed, though the "mail by" language is not something I feel comfortable changing across the board. I understand the quibble though. Next time, we'll get more specific about this stuff.
