### ISSUE TITLE
Arizona voting info

### ISSUE THREAD

**Issue by hobbes7878** [The-Politico/politico-civic-almanac#23]
>Please check your facts on who is eligible to vote in Arizona primaries.  Unless something has changed, Arizona primaries are closed primaries.  Meaning you can only vote for candidates in the party in which you are registered.
>
> Thank you,
> 
> Arthur Schwartz
> Tucson, AZ

**Comment by TylerFisher** [comment]
This is incorrect. Presidential primaries are closed, but congressional primaries are not. If you are not registered to a party, you can choose any party's ballot. See [here].(http://www.yavapai.us/electionsvr/faqs/what-does-arizonas-open-primary-law-mean)
